# Generated by Django 5.1.5 on 2025-04-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_job_company_logo_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='skills',
            new_name='skill',
        ),
    ]
