# Generated by Django 5.1.5 on 2025-04-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_skills_customuser_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='skill',
            new_name='skills',
        ),
    ]
