# Generated by Django 5.1.5 on 2025-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_skill_customuser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
