# Generated by Django 5.1.5 on 2025-05-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_job_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='skill',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
